# Generated by Django 3.1.6 on 2021-03-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotext',
            name='user',
        ),
        migrations.AlterField(
            model_name='todotext',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
